---
title: "Consensus Community Detection"
description: |
  Typical use of Consensus Community Detection package.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Consensus Community Detection}
  %\VignetteEncoding{UTF-8}
---
 

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

# introduction
This vignette shows the typical usage of the CCD library.

## installation
the library can be downloaded and installed from GitHub https://github.com/fabio-morea/CCD


```{r load library, message=FALSE, warning=FALSE}
#library(devtools)  
#devtools::install_github("fabio-morea/CCD")
library(CCD)
library(igraph)
library(tidyverse)
library(aricode)
```


The package contains two sample networks: `roc45bc` and `roc84bc`.

## example of community detection
A toy network to test community detection: ring of cliques.

```{r}
plot(roc45bc)
```

```{r c1, echo=TRUE}
comm <- cluster_louvain(roc45bc) 
print(comm$membership)
plot(comm, roc45bc)
 

```
```{r}

comm <- CCD::consensus_community_detection(roc45bc,
                              t=100, 
                              method='LV', 
                              p = 0.8, 
                              q=.5,
                              shuffle = T)
print(comm$gamma)
plot(comm, roc45bc)
plot(roc45bc, 
     vertex.size = 30,
     vertex.label = comm$gamma,
     vertex.color = if_else(comm$gamma > .2,"yellow", "green"))
```


Second example: a larger network. 
```{r c2, echo=TRUE}
comm <- CCD::consensus_community_detection(roc84bc,
                              t=100, 
                              method='LV',
                              r = 1.0,
                              p = 0.60, 
                              q=.5,
                              shuffle = T)
plot(comm, roc84bc)


```

```{r}
plot(comm, roc84bc, vertex.label = NA)
```

```{r}
plot(roc84bc, 
     vertex.size = 30,
     vertex.label = comm$gamma,
     vertex.color = if_else(comm$gamma > .2,"yellow", "green"))

```


## analysis of communities
 

```{r}
#setting the parameters
V(roc84bc)$community <- comm$membership
E(roc84bc)$w <- E(roc84bc)$weight
# build the community network
gc <- make_community_network(roc84bc)
#plot
plot(gc, vertex.size = V(gc)$size*10, 
     vertex.label = V(gc)$size)
```

 