---
title: 'create simple graphs to test Consensus Community Detection'
output:
  pdf_document: default
  html_notebook: default
---
 


```{r load libraries, include=FALSE}
library(igraph)
```

```{r}
make_clique <- function(clique_size, comm_label) {
  G <- graph.empty(n = clique_size)
  edges <- t(combn(1:clique_size, 2))
  for (e in 1:nrow(edges)) {
      G <- add_edges(G, edges[e, ])
  }
  V(G)$community <- comm_label
  return(as.undirected(G))
}
```


```{r}
make_ring_of_cliques <- function(num_cliques,
                                 clique_size,
                                 add_center = TRUE,
                                 add_bridges = TRUE,
                                 filename = '') {
  
    G <- as.undirected(graph.empty())
  
  for (i in 1:num_cliques) {
    next_clique <- make_clique(clique_size, comm_label = paste0("C", i))
    G <- G + next_clique
  }
  
   b <- vcount(G)
  if (add_bridges) {
    G <- add_vertices(G, num_cliques)
  }
  
  
  for (j in 1:(num_cliques)) {
    b <- b + 1
    b_start <- (j-1) * clique_size +1
    b_end <- b_start + clique_size +1
    if (b_end > (clique_size * num_cliques)) {b_end <- 2}
    if (add_bridges) {
      
      G <- add_edges(G, c(b_start, b))
      G <- add_edges(G, c(b, b_end))
      V(G)$community[b] <- paste0("B", j)
    } else {
      G <- add_edges(G, c(b_start, b_end))
    }
    
  }
  
  if (add_center) {
    G <- add_vertices(G, 1)
    id_center <- vcount(G)
    V(G)$community[id_center] <- "A"
    for (j in 1:(num_cliques)) {
      c_start <- (j-1) * clique_size +3
      G <- add_edges(G, c(c_start , id_center))
    }
    
  }
  
  
  E(G)$weight <- 1.0
  V(G)$id <- seq(1:vcount(G))
  V(G)$name <- V(G)$id 

  
  if (filename != '') {write_graph(G, paste0(filename, '.gml'), format = 'gml')}
  
  return(G)
  
}


```


```{r}
roc84bc <- make_ring_of_cliques(
    num_cliques = 8,
    clique_size = 4,
    add_center = TRUE,
    add_bridges = TRUE,
    filename = ''
)
save(roc84bc, file = "data/roc84bc.rda")
print(roc84bc)
```
```{r}
roc45bc <- make_ring_of_cliques(
    num_cliques = 4,
    clique_size = 5,
    add_center = TRUE,
    add_bridges = TRUE,
    filename = ''
)
save(roc45bc, file = "data/roc45bc.rda")
print(roc45bc)

```
```{r}
plot(roc45bc)
```
 
```{r}
plot(roc84bc)
```

