---
title: 'vignette: Consensus Community Detection'
output:
  pdf_document: default
  html_notebook: default
---

# introduction
This notebook shows the typical usage of che CCD library.

## installation
the library can be downloaded and installed from GitHub https://github.com/fabio-morea/CCD
```{r} 
library(devtools)  
install_github("fabio-morea/CCD")
library(CCD)
?consensus_community_detection
```

data has been loaded with lazyload: it is visible in CCD package as "promise" and loaded at first use.


```{r}
comm <- consensus_community_detection(roc45bc,
                              t=100, 
                              method='LV', 
                              gamma_lim = 0.6)
plot(comm,roc45bc )
plot(roc45bc, vertex.color = if_else(comm$gamma > .01,"red", "green"))

```

```{r}
comm <- consensus_community_detection(roc84bc,
                              t=100, 
                              method='LV', 
                              gamma_lim = 0.6)
comm$gamma
plot(comm, roc84bc)
plot(roc84bc, vertex.color = if_else(comm$gamma > .01,"red", "green"))

```


 